name: Mrlonely-BLOGS
on:
  push:
    branches:
      - main  # 触发部署的分支
  pull_request:

jobs:
  build:
    name: Build Test
    runs-on: Ubuntu 22.04.4 LTS
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up `pnpm`
        uses: pnpm/action-setup@v4
        with:
          run_install: true

      - name: Build
        run: pnpm build

      - name: Deploy to Alibaba Cloud
        uses: aliyun/alicloud-action@v1
        with:
          access-key-id: ${{ secrets.ACCESSKEYID }}
          access-key-secret: ${{ secrets.ACCESSKEYSECRET }}
          instance-id: ${{secrets.INSTANCEID}}
          source-dir: 'build'  # 构建生成的目录
