name: Mrlonely-BLOGS
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Setup Corepack
        run: corepack enable
  
      - name: Install dependencies
        run: pnpm i

      # - name: Set up `pnpm`
      #   uses: pnpm/action-setup@v4
      #   with:
      #     run_install: true

      - name: Build
        run: pnpm build

      - name: Deploy to Alibaba Cloud
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.ALIYUN_SERVER_IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.BLOGPRIVATEKEY }}
          password: ${{ secrets.PASSWORD }}
          # access-key-id: ${{ secrets.ACCESSKEYID }}
          # access-key-secret: ${{ secrets.ACCESSKEYSECRET }}
          # instance-id: ${{secrets.INSTANCEID}}
          source: '.vitepress/dist'  # 构建生成的目录
          target: /usr/share/caddy/blog
